- type: accessLevel
  id: HeadOfSecurity
  name: id-card-access-level-head-of-security
  canBeSwitchableInReader: false #SS220 DoorElectronicsConfiguratorFix

- type: accessLevel
  id: Security
  name: id-card-access-level-security
  canBeSwitchableInReader: false #SS220 DoorElectronicsConfiguratorFix

- type: accessLevel
  id: Armory
  name: id-card-access-level-armory
  canBeSwitchableInReader: false #SS220 DoorElectronicsConfiguratorFix

- type: accessLevel
  id: Brig
  name: id-card-access-level-brig
  canBeSwitchableInReader: false #SS220 DoorElectronicsConfiguratorFix

- type: accessLevel
  id: Detective
  name: id-card-access-level-detective

- type: accessGroup
  id: Security
  tags:
  - HeadOfSecurity
  - Security
  - Armory
  - Brig
  - Detective
  - Cryogenics

- type: accessGroup
  id: Armory
  tags:
  - Security
  - Armory
  - Brig
