- type: department
  id: InternalAffairs
  name: department-InternalAffairs
  sort: 0
  description: department-Internal-Affairs-description
  color: "#323ba9"
  roles:
  - IAA
  - BlueShield
  - Lawyer
  - Detective
  primary: false
  weight: 80
