- type: job
  id: SecurityOfficer
  name: job-name-security
  description: job-description-security
  playTimeTracker: JobSecurityOfficer
  requirements:
    - !type:DepartmentTimeRequirement
      department: Security
      time: 36000 # SS220-RoleTime
  startingGear: SecurityOfficerGear
  icon: "JobIconSecurityOfficer"
  supervisors: job-supervisors-hos
  canBeAntag: false
  access:
  - Security
  - Brig
  - Maintenance
  - Service
  - External
  - Cryogenics
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: SecurityOfficerGear
  equipment:
    eyes: ClothingEyesGlassesSecurity
    ears: ClothingHeadsetSecurity
    pocket1: WeaponPistolMk58Nonlethal # SS220 Bring-Rubber-Back
  storage:
    back:
    - Flash
    - MagazinePistolRubber #SS220-DeleteSecurityLetal-Begin
    - MagazinePistolRubber
    - FlashlightSeclite
    - DrinkRelaxingPeachCan #SS220-DeleteSecurityLetal-End
