- type: job
  id: Warden
  name: job-name-warden
  description: job-description-warden
  playTimeTracker: JobWarden
  requirements:
    - !type:DepartmentTimeRequirement
      department: Security
      time: 108000 # SS220-RoleTime
    - !type:SpeciesRequirement #SS220-jobbans begin
      inverted: true
      species:
      - Felinid #SS220-jobbans end
  startingGear: WardenGear
  icon: "JobIconWarden"
  requireAdminNotify: true
  supervisors: job-supervisors-hos
  canBeAntag: false
  access:
  - Security
  - Brig
  - Armory
  - Maintenance
  - Service
  - External
  - Detective
  - Cryogenics
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: WardenGear
  equipment:
    eyes: ClothingEyesGlassesSecurity
    id: WardenPDA
    ears: ClothingHeadsetSecurity
#    belt: ClothingBeltSecurityFilled #SS220-FreedomHoSCap
    pocket1: WeaponPistolMk58Nonlethal #SS220-DeleteSecurityLetal
  storage:
    back:
    - Flash
    - MagazinePistolRubber #SS220-DeleteSecurityLetal-Begin
    - MagazinePistolRubber
    - FlashlightSeclite
    - DrinkRelaxingPeachCan #SS220-DeleteSecurityLetal-End
