- type: department
  id: Cargo
  description: department-Cargo-description
  color: "#A46106"
  sort: 0
  roles:
  - CargoTechnician
  - Quartermaster
  - SalvageSpecialist

- type: department
  id: Civilian
  description: department-Civilian-description
  color: "#9FED58"
  weight: -10
  roles:
  - Bartender
  - Borg
  - Botanist
  - Boxer
  - Chaplain
  - Chef
  - Clown
  - Detective
  - HeadOfPersonnel
  - SeniorService #ss220-SEniorService
  - Janitor
  - Lawyer
  - Librarian
  - Mime
  - Musician
  - Passenger
  - Reporter
  - Visitor
  - Zookeeper
  - ServiceWorker

- type: department
  id: Command
  sort: 1
  description: department-Command-description
  color: "#052EED"
  roles:
  - Captain
  - IAA # Corvax-IAA
  - CentralCommandOfficial
  - ChiefEngineer
  - ChiefMedicalOfficer
  - HeadOfPersonnel
  - HeadOfSecurity
  - ResearchDirector
  - Quartermaster
  - BlueShield
  primary: false
  weight: 100

- type: department
  id: Engineering
  sort: 0
  description: department-Engineering-description
  color: "#EFB341"
  roles:
  - AtmosphericTechnician
  - ChiefEngineer
  - SeniorEngineer #ss220
  - StationEngineer
  - TechnicalAssistant

- type: department
  id: Medical
  sort: 0
  description: department-Medical-description
  color: "#52B4E9"
  roles:
  - Chemist
  - ChiefMedicalOfficer
  - SeniorPhysician #ss220
  - MedicalDoctor
  - MedicalIntern
  - Psychologist
  - Paramedic
  - Brigmedic #ss220-brigmed

- type: department
  id: Security
  sort: 0
  description: department-Security-description
  color: "#DE3A3A"
  weight: 20
  roles:
  - HeadOfSecurity
  - SeniorOfficer #ss220
  - SecurityCadet
  - SecurityOfficer
  - Warden
  - SecurityPilot

- type: department
  id: Science
  sort: 0
  description: department-Science-description
  color: "#D381C9"
  roles:
  - ResearchDirector
  - SeniorResearcher #ss220
  - Scientist
  - ResearchAssistant

- type: department
  id: Cryo
  sort: 0
  description: Крио
  color: "#88FF88"
  roles: []
  primary: false
  weight: -50


- type: department
  id: Specific
  sort: 0
  description: department-Specific-description
  color: "#9FED58"
  weight: 10
  roles:
  - Boxer
  - Reporter
  - Zookeeper
#  - Psychologist SS220-psychologist-chat-color-fix
  primary: false

- type: department
  id: GhostRoles
  sort: 0
  description: Ghost roles
  color: "#A9A9A9"
  roles:
  - GhostRole
  primary: false
  weight: -100
