- type: job
  id: Quartermaster
  name: job-name-qm
  description: job-description-qm
  playTimeTracker: JobQuartermaster
  requirements:
    - !type:DepartmentTimeRequirement
      department: Cargo
      time: 108000 # SS220-RoleTime
    - !type:RoleTimeRequirement
      role: JobSalvageSpecialist
      time: 18000 # SS220-RoleTime 2
    - !type:OverallPlaytimeRequirement
      time: 180000 # SS220-RoleTime
    - !type:AgeRequirement
      requiredAge: 20
    - !type:SpeciesRequirement #SS220-jobbans begin
      inverted: true
      species:
      - Felinid #SS220-jobbans end
  weight: 10
  startingGear: QuartermasterGear
  icon: "JobIconQuarterMaster"
  supervisors: job-supervisors-captain
  access:
  - Cargo
  - Salvage
  - Quartermaster
  - Maintenance
  - Command
  - Brig
  - Cryogenics
  special:
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff

- type: startingGear
  id: QuartermasterGear
  equipment:
    id: QuartermasterPDA
    ears: ClothingHeadsetQM
    belt: BoxFolderClipboard
    pocket1: AppraisalTool
  storage:
    back:
    - Flash
