- type: antag
  id: HeadRev
  name: roles-antag-rev-head-name
  antagonist: true
  setPreference: true
  objective: roles-antag-rev-head-objective
  guides: [ Revolutionaries ]
  #SS220 Add antags playtime trackers begin
  playTimeTracker: AntagHeadRev
  antagColor: CornflowerBlue
  #SS220 Add antags playtime trackers end

- type: antag
  id: Rev
  name: roles-antag-rev-name
  antagonist: true
  setPreference: false
  objective: roles-antag-rev-objective
  guides: [ Revolutionaries ]

- type: startingGear
  id: HeadRevGear
  storage:
    back:
    - Flash
    - ClothingEyesGlassesSunglasses
