- type: antag
  id: Thief
  name: roles-antag-thief-name
  antagonist: true
  setPreference: true
  objective: roles-antag-thief-objective
  guides: [ Thieves ]
  #SS220 Add antags playtime trackers begin
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 72000 # 20h SS220 time
  playTimeTracker: AntagThief
  #SS220 Add antags playtime trackers end

- type: startingGear
  id: ThiefGear
  storage:
    back:
    - ToolboxThief
    - ClothingHandsChameleonThief
    - ThiefBeacon
