# Just equipment preset, no custom role

- type: startingGear
  id: CentcomAdmiralGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitCentcomAdmiral
    shoes: ClothingShoesBootsJack
    head: ClothingHeadCapCentcomNaval
    eyes: ClothingEyesGlassesSecurity #ss-220-GlassesSecurity
    gloves: ClothingHandsGlovesCentcomNaval
    outerClothing: ClothingOuterArmorCentcomCarapace
    neck: ClothingNeckCloakCentcomAdmiral
    id: CentcomPDA
    ears: ClothingHeadsetCentCom
    pocket1: RubberStampCentcom
  inhand:
    - TelescopicShield #SS220-new-centcomm
